name: Service · Check

on:
  workflow_call:
    inputs:
      path: { required: true, type: string }
      image: { required: true, type: string }

permissions:
  contents: read
  actions: write
  pull-requests: read
  checks: write

jobs:
  init:
    name: Init
    uses: grootan-devops/github-ci-library/.github/workflows/init.yml@mono-repo-dev
    secrets: inherit
    with:
      project-path: ${{ inputs.path }}
      image-repository: ${{ inputs.image }}
      ignore-chart: "true"
      ignore-docker: "false"

  check:
    name: Guards
    needs: init
    uses: grootan-devops/github-ci-library/.github/workflows/check.yml@mono-repo-dev
    secrets: inherit
    with:
      tag: ${{ needs.init.outputs.tag }}
      image-tag: ${{ needs.init.outputs.image-tag }}
      image-repository: ${{ needs.init.outputs.image-repository }}
      project-path: ${{ inputs.path }}
      check-migration: false
