name: MonoProbeChild
on:
  workflow_call:
    inputs:
      name: { required: true, type: string }
      path: { required: true, type: string }
      image: { required: true, type: string }
jobs:
  init:
    uses: grootan-devops/github-ci-library/.github/workflows/init.yml@mono-repo-dev
    secrets: inherit
    with:
      project-path: ${{ inputs.path }}
      image-repository: ${{ inputs.image }}
      ignore-chart: "true"
      ignore-docker: "false"
